### ISSUE TITLE
Tutorial 5：在开启sti的时候VirtualBox崩溃

### ISSUE THREAD

**Issue by l1cacheDell** [yukinoHyj/YUKI#1]
你好~我也是这个教程的学习者，目前学到Tutorial 5，也就是`printf('INTERRUPT');`的地方，现在就是我发现运行的时候会导致VirtualBox崩溃，不知道是哪里的问题。不知道您有没有遇到类似的问题？

Detail: 运行OS成功（无输入状态），现在向虚拟机中进行键盘输入，如果正常应该有 `INTERRUPT`打印输出，但是我的OS在接收键盘输入的时候直接crush了，也不知道原因在什么地方。

**Comment by ShimokitaYui** [comment]
能把你的代码发来看一下么或者截图什么的

**Comment by ShimokitaYui** [comment]
在教程中，出现开启中断后系统崩溃可能是GDT中指针指向错误的位置让CPU崩溃

**Comment by ShimokitaYui** [comment]
你可以看一下我写的操作系统编写问题总集 可能是一样的问题 你可以试着改一下试试看

**Comment by l1cacheDell** [comment]
谢谢大哥，问题解决了！
